### ISSUE TITLE
After some paypal transaction there is no response (appointed or paid) getting

### ISSUE THREAD

**Issue by iamsarath1986** [fjbender/simple-php-integration#11]
I have implemented the payone payment gateway (creditcard, sofort, paydirect and paypal). After successfull payment I am getting txaction response like "appointed" and "paid". But I am not getting response from payone after customer paid using paypal (Not every paypal transaction. On 20 successful transaction 2 or 3 are not giving response. But customer amount has been deducted from his account).

if ($_POST["key"] == hash("md5", 'KEY')) {
 echo "TSOK";

 Here I check the user data is matching with $_POST["userid"].
 $user = result of matching user.

if($user && $_POST["clearingtype"] && $_POST["txaction"]) {
  if ($_POST["txaction"] == "appointed") {
    update booking status and sent email
  }
  else if ($_POST["txaction"] == "paid") {
    update paid status
  }
  else {
    update failed status
   }
}

I called payone support and not found the reason. Any help would be appreciated thanks.

**Comment by fjbender** [comment]
This probably is an issue between PayPal and our platform, and not an issue with your PHP integration. I'm afraid I can't help you with this. :/

**Comment by iamsarath1986** [comment]
@fjbender Thank you for your response.
