### ISSUE TITLE
Do you have example in python?

### ISSUE THREAD

**Issue by hyzhak** [fjbender/simple-php-integration#3]
Hello! I'm developing python app and like to do integration with payone but lack of good documentation and examples in python for payone. Do you have them?

**Comment by fjbender** [comment]
Sorry, I don't have any. Feel free to provide some in a pull request :)

**Comment by hyzhak** [comment]
@fjbender sure, but my python code doesn't work,  here is it http://stackoverflow.com/questions/41742455/verifying-credit-cards-creditcardcheck-on-payone-with-python

**Comment by fjbender** [comment]
@hyzhak see my answer in the stackoverflow thread.

**Comment by hyzhak** [comment]
@fjbender thanks for answer! But I'm using sha2-384 instead, because it is recommended in a docs.

**Comment by fjbender** [comment]
@hyzhak did you configure it accordingly in the pmi?

**Comment by hyzhak** [comment]
@fjbender yes, I have setup it here https://pmi.pay1.de/merchants/?navi=portal&rc=1

**Comment by hyzhak** [comment]
<img width="1061" alt="screen shot 2017-01-19 at 16 12 24-2" src="https://cloud.githubusercontent.com/assets/184706/22114276/2a290eb4-de69-11e6-9077-30cabc8a55d7.png">

**Comment by hyzhak** [comment]
<img width="1061" alt="screen shot 2017-01-19 at 16 12 24-2" src="https://cloud.githubusercontent.com/assets/184706/22114814/0d53f482-de6b-11e6-9a39-8dcb67bc538b.png">

**Comment by fjbender** [comment]
@hyzhak Did it work with md5 nonetheless?

**Comment by hyzhak** [comment]
@fjbender ok, md5 works for me only without `api_version` parameter http://stackoverflow.com/questions/41742455/verifying-credit-cards-creditcardcheck-on-payone-with-python/41805520#41805520 so it looks like typo in documentation. Now I'm going to check sha384.

**Comment by hyzhak** [comment]
yes, `sha384` works without `api_version` too
