### ISSUE TITLE
Parameter {request} faulty or missing

### ISSUE THREAD

**Issue by ghost** [fjbender/simple-php-integration#6]
Hi,

I implemented the code from you in my magento store, but when I send the request to payone I got every time this error:

`string(166) "status=ERROR errorcode=1202 errormessage=Parameter {request} faulty or missing customermessage=An error occured while processing this transaction (wrong parameters). " `

My request looks like this:
`string(244) "{"aid":"xxxxx","mid":"xxxx","portalid":"xxxxx","key":"xxxxx","api_version":"3.9","mode":"test","encoding":"UTF-8","request":"cancelation","txid":"xxxxx","sequencenumber":"1","amount":"85.9000","currency":"EUR"}" `

I'm not sure if "cancelation" is a valid request, but I also tried with "capture" and there is the same error. Have you an idea what's my problem?

Best regards,
Fabian

**Comment by fjbender** [comment]
Hi Fabian,

in this case I'd advise you contact our Technical Support Team who'll gladly help you with implementing the Payone API on your own. This implementation is just an example and meant to be read with the Server-API description ready for reference.

For starters, you might want to create a transaction first by using the authorization or preauthoriztaion request. Also please note that the amount has to be given as an integer in the smallest currency unit, as noted in the simple PHP integration document.

Best
Florian
